export const environment = {
  production: true,
  LOGIN_URL: 'https://test.obdii.io:3000/',
  LOGOUT_URL: 'https://test.obdii.io:3000/',
  SERVER_URL: 'https://test.obdii.io:3000/api/v1/',
  POD_SERVER_URL: 'https://test.obdii.io',
  ANGULAR_SERVER_URL: 'https://test.obdii.io',
  POD_SERVER_PORT: '5000',
  ANGULAR_PORT: '3000',
  POD_SERVER_ROOM: '/pod',
  heartBeat: 30000,
  deviceControl: 30000,
  scanstartText: 'Start Procedure:::',
  STORE_LOGIN: '/auth/authlogin',
  STORE_URL: 'https://store.obdii.io',
  STORE_LOGOUT: '/index.php/customer/account/logout',
};